#!/usr/bin/env python3
"""Deterministic HTCondor sweep runner for the autoresearch campaign.

Expands a YAML grid spec into HTCondor jobs, submits via condor_submit_bid,
waits, and aggregates per-job .npy results into TSV tables.

No LLM calls, no git operations, no adaptive logic — judgment belongs to the
orchestrating Claude instance (see autoresearch/PROGRAM.md).

Usage:
    python cluster/sweep_runner.py grid.yaml                # submit + wait + aggregate
    python cluster/sweep_runner.py grid.yaml --mode dry     # expand + print only
    python cluster/sweep_runner.py grid.yaml --mode local --limit 1  # sanity run
    python cluster/sweep_runner.py grid.yaml --aggregate-only        # re-aggregate
"""
from __future__ import annotations

import argparse
import itertools
import re
import subprocess  # nosec B404
import sys
from pathlib import Path

import numpy as np
import yaml

REQUIRED_KEYS = {"round", "script", "grid"}
DEFAULT_RESOURCES = {"cpus": 4, "memory_gb": 16, "disk_gb": 10, "max_time_s": 86400}
DEFAULT_BID = 43
MAX_JOBS_WITHOUT_CONFIRM = 200

SUB_TEMPLATE = """\
# Auto-generated by sweep_runner.py for round {round} — regenerate, don't edit.
universe = vanilla
executable = cluster/run_autoresearch_job.sh
initialdir = {project_dir}
getenv = True

request_cpus = {cpus}
request_memory = {memory_gb} GB
request_disk = {disk_gb} GB

MaxTime = {max_time_s}
+MaxRuntime = {max_time_s}
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

log = {condor_dir}/sweep.log
output = {condor_dir}/job_$(jobidx).out
error = {condor_dir}/job_$(jobidx).err

arguments = "$(jobidx) $(jobscript) $(joboutdir) $(jobargs)"
queue jobidx,jobscript,joboutdir,jobargs from {pending_file}
"""


def load_spec(path: str | Path) -> dict:
    with open(path, encoding="utf-8") as f:
        spec = yaml.safe_load(f)
    missing = REQUIRED_KEYS - set(spec)
    if missing:
        raise ValueError(f"grid spec missing required keys: {sorted(missing)}")
    if not isinstance(spec["grid"], dict) or not spec["grid"]:
        raise ValueError("grid must be a non-empty mapping of flag -> list of values")
    spec.setdefault("base_args", "")
    spec.setdefault("output_flag", "--output_dir")
    spec.setdefault("bid", DEFAULT_BID)
    resources = dict(DEFAULT_RESOURCES)
    resources.update(spec.get("resources", {}))
    spec["resources"] = resources
    return spec


def expand_grid(grid: dict) -> list[str]:
    """Cartesian product of grid values -> arg strings, deterministic order."""
    keys = sorted(grid)
    jobs = []
    for combo in itertools.product(*(grid[k] for k in keys)):
        parts = []
        for key, value in zip(keys, combo):
            flag = key if key.startswith("--") else f"--{key}"
            if isinstance(value, bool):
                if value:
                    parts.append(flag)
            elif isinstance(value, (list, tuple)):
                parts.append(f"{flag} {' '.join(str(v) for v in value)}")
            else:
                parts.append(f"{flag} {value}")
        args = " ".join(parts)
        if "," in args:
            raise ValueError(f"comma not allowed in args (breaks condor queue-from): {args}")
        jobs.append(args)
    return jobs


def pending_jobs(jobs: list[str], results_root: Path, force: bool = False) -> list[tuple[int, str]]:
    out = []
    for idx, args in enumerate(jobs):
        if not force and (results_root / f"job_{idx:04d}" / "DONE").exists():
            continue
        out.append((idx, args))
    return out


def generate_sub(spec: dict, project_dir: Path, results_root: Path, pending_file: Path) -> str:
    condor_dir = results_root / "condor"
    return SUB_TEMPLATE.format(
        round=spec["round"],
        project_dir=project_dir,
        condor_dir=condor_dir,
        pending_file=pending_file,
        **spec["resources"],
    )


def aggregate(results_root: Path) -> list[dict]:
    rows = []
    for job_dir in sorted(results_root.glob("job_*")):
        row: dict = {"job": job_dir.name, "done": (job_dir / "DONE").exists()}
        for npy in sorted(job_dir.rglob("*.npy")):
            stem = npy.stem
            try:
                # allow_pickle: these .npy files are dict payloads written by our
                # own experiment scripts on our own cluster (repo result format),
                # never third-party input.
                data = np.load(npy, allow_pickle=True)
            except Exception as exc:  # noqa: BLE001  pylint: disable=broad-exception-caught
                row[f"{stem}:load_error"] = str(exc)
                continue
            payload = data.item() if getattr(data, "shape", None) == () else None
            if isinstance(payload, dict):
                for key, value in payload.items():
                    if np.isscalar(value) or (hasattr(value, "shape") and value.shape == ()):
                        try:
                            row[f"{stem}.{key}"] = float(value)
                        except (TypeError, ValueError):
                            row[f"{stem}.{key}"] = str(value)
                    else:
                        row[f"{stem}.{key}"] = f"shape={getattr(value, 'shape', type(value).__name__)}"
            else:
                row[stem] = f"shape={getattr(data, 'shape', '?')}"
        rows.append(row)
    return rows


def write_tsv(rows: list[dict], path: Path) -> None:
    keys: list[str] = []
    for row in rows:
        for key in row:
            if key not in keys:
                keys.append(key)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\t".join(keys) + "\n")
        for row in rows:
            f.write("\t".join(str(row.get(k, "")) for k in keys) + "\n")


def _build_lines(spec: dict, pend: list[tuple[int, str]], results_root: Path) -> list[str]:
    lines = []
    for idx, args in pend:
        outdir = results_root / f"job_{idx:04d}"
        full_args = " ".join(x for x in [spec["base_args"], args] if x)
        if spec["output_flag"]:
            full_args = f"{full_args} {spec['output_flag']} {outdir}"
        lines.append(f"{idx:04d},{spec['script']},{outdir},{full_args}")
    return lines


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("spec", help="YAML grid spec (see autoresearch/PROGRAM.md)")
    ap.add_argument("--mode", choices=["condor", "dry", "local"], default="condor")
    ap.add_argument("--force", action="store_true", help="re-run jobs with DONE markers")
    ap.add_argument("--limit", type=int, default=None, help="only first N pending jobs")
    ap.add_argument("--aggregate-only", action="store_true")
    ap.add_argument("--yes-many", action="store_true", help=f"allow >{MAX_JOBS_WITHOUT_CONFIRM} jobs")
    args = ap.parse_args(argv)

    spec = load_spec(args.spec)
    project_dir = Path.cwd()
    results_root = project_dir / "autoresearch" / "results" / spec["round"]

    if args.aggregate_only:
        rows = aggregate(results_root)
        write_tsv(rows, results_root / "summary.tsv")
        n_done = sum(bool(r["done"]) for r in rows)
        print(f"aggregated {len(rows)} job(s), {n_done} DONE -> {results_root / 'summary.tsv'}")
        return 0

    jobs = expand_grid(spec["grid"])
    pend = pending_jobs(jobs, results_root, force=args.force)
    if args.limit is not None:
        pend = pend[: args.limit]
    print(f"{len(jobs)} job(s) in grid, {len(pend)} pending [{args.mode.upper()}]")
    if not pend:
        print("nothing to do (all DONE; use --force to re-run)")
        return 0
    if len(pend) > MAX_JOBS_WITHOUT_CONFIRM and not args.yes_many:
        print(f"refusing to submit {len(pend)} > {MAX_JOBS_WITHOUT_CONFIRM} jobs without --yes-many")
        return 2

    lines = _build_lines(spec, pend, results_root)
    if args.mode == "dry":
        for line in lines:
            print(f"  {line}")
        return 0

    results_root.mkdir(parents=True, exist_ok=True)
    (results_root / "condor").mkdir(exist_ok=True)
    manifest_rows = [{"idx": i, "args": a, "status": "submitted"} for i, a in pend]

    if args.mode == "local":
        for line in lines:
            idx, script, outdir, job_args = line.split(",", 3)
            Path(outdir).mkdir(parents=True, exist_ok=True)
            print(f"[local] job {idx}: python {script} {job_args}")
            result = subprocess.run(  # nosec B603
                [sys.executable, script] + job_args.split(), cwd=project_dir, check=False
            )
            status = "done" if result.returncode == 0 else f"failed({result.returncode})"
            if result.returncode == 0:
                (Path(outdir) / "DONE").touch()
            manifest_rows[[r["idx"] for r in manifest_rows].index(int(idx))]["status"] = status
    else:  # condor
        pending_file = results_root / "pending.txt"
        pending_file.write_text("\n".join(lines) + "\n")
        sub_file = results_root / "sweep.sub"
        sub_file.write_text(generate_sub(spec, project_dir, results_root, pending_file))
        submit = subprocess.run(  # nosec B603 B607
            ["condor_submit_bid", str(spec["bid"]), str(sub_file)],
            capture_output=True,
            text=True,
            check=True,
        )
        print(submit.stdout.strip())
        match = re.search(r"cluster (\d+)", submit.stdout)
        cluster_id = match.group(1) if match else None
        log_file = results_root / "condor" / "sweep.log"
        timeout = spec["resources"]["max_time_s"] + 3600
        wait_cmd = ["condor_wait", "-wait", str(timeout), str(log_file)]
        if cluster_id:
            wait_cmd.append(cluster_id)
        print(f"waiting on {log_file} (timeout {timeout}s) ...")
        subprocess.run(wait_cmd, check=False)  # nosec B603 B607
        for row in manifest_rows:
            done = (results_root / f"job_{row['idx']:04d}" / "DONE").exists()
            row["status"] = "done" if done else "failed-or-held"

    write_tsv(manifest_rows, results_root / "jobs_manifest.tsv")
    rows = aggregate(results_root)
    write_tsv(rows, results_root / "summary.tsv")
    n_done = sum(bool(r["done"]) for r in rows)
    n_fail = len(manifest_rows) - sum(r["status"] == "done" for r in manifest_rows)
    print(f"summary: {n_done}/{len(rows)} job dirs DONE, {n_fail} failed/held")
    print(f"-> {results_root / 'summary.tsv'}")
    return 1 if n_fail else 0


if __name__ == "__main__":
    sys.exit(main())
